repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      # - id: terrascan # https://github.com/tenable/terrascan
      # - id: tfupdate # https://github.com/minamijoyo/tfupdate
      # - id: terraform_checkov # https://github.com/bridgecrewio/checkov
      - id: terraform_docs
